// Generated by CoffeeScript 1.7.1
(function() {
  var app, bodyParser, cookieParser, express, flash, middleware, mongoose, morgan, passport, path, port, session;

  express = require('express');

  app = express();

  port = process.env.PORT || 8080;

  path = require('path');

  mongoose = require('mongoose');

  passport = require('passport');

  flash = require('connect-flash');

  morgan = require('morgan');

  cookieParser = require('cookie-parser');

  bodyParser = require('body-parser');

  session = require('express-session');

  middleware = require('./config/middleware');

  require('./config/db');

  require('./config/passport')(passport);

  app.use(morgan('dev'));

  app.use(cookieParser());

  app.use(bodyParser());

  app.set('views', path.join(__dirname, 'views'));

  app.set('view engine', 'jade');

  app.use(session({
    secret: 'mysecret'
  }));

  app.use(passport.initialize());

  app.use(passport.session());

  app.use(flash());

  require('./routes/routes')(app, passport);

  app.listen(port);

  console.log('Magic happens on port ' + port);

}).call(this);
