// Generated by CoffeeScript 1.7.1
(function() {
  var app, bodyParser, dbURI, express, mongoose, port, router;

  express = require('express');

  app = express();

  bodyParser = require('body-parser');

  mongoose = require('mongoose');

  dbURI = 'mongodb://localhost/todo';

  mongoose.connect(dbURI);

  app.use(bodyParser.urlencoded({
    extended: true
  }));

  port = process.env.PORT || 8080;

  router = express.Router();

  router.get('/', function(req, res) {
    return res.json({
      message: 'hooray! welcome to our api!'
    });
  });

  app.use('/api', router);

  app.listen(port);

  console.log('Magic happens on port ' + port);

}).call(this);
