// Generated by CoffeeScript 1.7.1
(function() {
  var express;

  express = require('express');

  exports.home = function(req, res) {
    return res.render('index.jade', {
      title: 'Todo'
    });
  };

  exports.login = function(req, res) {
    return res.render('login.jade', {
      title: 'Login'
    });
  };

  exports.signup = function(req, res) {
    return res.render('signup.jade', {
      title: 'Sign Up'
    });
  };

}).call(this);
