// Generated by CoffeeScript 1.7.1
(function() {
  var express;

  express = require('express');

  exports.home = function(req, res) {
    return res.render('index.jade', {
      title: 'Todo',
      styles: ['css/landing.css']
    });
  };

  exports.login = function(req, res) {
    return res.render('login.jade', {
      title: 'Login',
      styles: []
    });
  };

  exports.signup = function(req, res) {
    return res.render('signup.jade', {
      title: 'Sign Up',
      styles: []
    });
  };

}).call(this);
