// Generated by CoffeeScript 1.7.1
(function() {
  var express;

  express = require('express');

  module.exports = function(app, passport) {
    var router;
    router = express.Router();
    router.get('/', function(req, res) {
      return res.render('index.jade', {
        title: 'Todo'
      });
    });
    return app.use('/', router);
  };

}).call(this);
