// Generated by CoffeeScript 1.7.1
(function() {
  var index, middleware, tasks, user;

  index = require('./index');

  user = require('./user');

  tasks = require('./tasks');

  middleware = require('./../config/middleware');

  module.exports = function(app, passport) {
    app.route('/').get(index.home);
    app.route('/login').get(index.login);
    app.route('/signup').get(index.signup);
    app.route('/signup').post(user.signup(passport));
    app.route('/login').post(user.login(passport));
    app.route('/logout').get(user.logout);
    return app.route('/api/tasks').all(middleware.requiresLogin).post(tasks.add).get(tasks.all);
  };

}).call(this);
