// Generated by CoffeeScript 1.7.1
(function() {
  var express, index, middleware, tasks, user;

  express = require('express');

  index = require('./index');

  user = require('./user');

  tasks = require('./tasks');

  middleware = require('./../config/middleware');

  module.exports = function(app, passport) {
    var api;
    app.route('/').get(index.home);
    app.route('/login').get(index.login).post(user.login(passport));
    app.route('/signup').get(index.signup).post(user.signup(passport));
    app.route('/logout').get(user.logout);
    api = express.Router();
    api.use(middleware.requiresLogin);
    api.route('/tasks').post(tasks.add).get(tasks.all);
    api.route('/tasks/:task_id').get(tasks.find).put(tasks.update)["delete"](tasks["delete"]);
    return app.use('/api', api);
  };

}).call(this);
