// Generated by CoffeeScript 1.7.1
(function() {
  var Task;

  Task = require('./../models/Task');

  exports.add = function(req, res) {
    var task;
    task = new Task();
    task.text = req.body.text;
    task.userID = req.user._id;
    return task.save(function(err) {
      if (err) {
        res.send(err);
      }
      return res.json({
        message: 'Task created! ',
        text: task.text,
        userID: task.userID
      });
    });
  };

  exports.all = function(req, res) {
    return Task.find({
      'userID': req.user._id
    }, function(err, tasks) {
      if (err) {
        res.send(err);
      }
      return res.json(tasks);
    });
  };

}).call(this);
