// Generated by CoffeeScript 1.7.1
(function() {
  var Task, express;

  express = require('express');

  Task = require('./../models/Task');

  module.exports = function(app) {
    var router;
    router = express.Router();
    router.route('/').post(function(req, res) {
      var task;
      task = new Task();
      task.text = req.body.text;
      return task.save(function(err) {
        if (err) {
          res.send(err);
        }
        return res.json({
          message: 'Task created! '
        });
      });
    }).get(function(req, res) {
      return Task.find(function(err, tasks) {
        if (err) {
          res.send(err);
        }
        return res.json(tasks);
      });
    });
    return app.use('/tasks', router);
  };

}).call(this);
