// Generated by CoffeeScript 1.7.1
(function() {
  var Task;

  Task = require('./../models/task');

  exports.add = function(req, res) {
    var task;
    task = new Task();
    task.text = req.body.text;
    task.userID = req.user._id;
    return task.save(function(err) {
      if (err) {
        res.send(err);
      }
      return res.json({
        message: 'Task created! ',
        text: task.text,
        userID: task.userID
      });
    });
  };

  exports.all = function(req, res) {
    return Task.find({
      'userID': req.user._id
    }, function(err, tasks) {
      if (err) {
        res.send(err);
      }
      return res.json(tasks);
    });
  };

  exports.find = function(req, res) {
    return Task.findOne({
      '_id': req.params.task_id,
      'userID': req.user._id
    }, function(err, task) {
      if (err) {
        res.send(err);
      }
      return res.json(task);
    });
  };

  exports.update = function(req, res) {
    return Task.findOne({
      '_id': req.params.task_id,
      'userID': req.user._id
    }, function(err, task) {
      if (err) {
        res.send(err);
      }
      task.text = req.body.text;
      return task.save(function(err) {
        if (err) {
          res.send(err);
        }
        return res.json(task);
      });
    });
  };

  exports["delete"] = function(req, res) {
    return Task.remove({
      '_id': req.params.task_id,
      'userID': req.user._id
    }, function(err, task) {
      if (err) {
        res.send(err);
      }
      return res.json({
        message: 'Task deleted'
      });
    });
  };

}).call(this);
