// Generated by CoffeeScript 1.7.1
(function() {
  var User, express;

  express = require('express');

  User = require('./../models/user');

  module.exports = function(app, passport) {
    var router;
    router = express.Router();
    router.post('/signup', passport.authenticate('local-signup', {
      successRedirect: '/success',
      failureRedirect: '/failure',
      failureFlash: true
    }));
    return app.use('/user', router);
  };

}).call(this);
