// Generated by CoffeeScript 1.7.1
(function() {
  var User, express;

  express = require('express');

  User = require('./../models/user');

  module.exports = function(app, passport) {
    var router;
    router = express.Router();
    router.post('/signup', passport.authenticate('local-signup', {
      successRedirect: '/user/success',
      failureRedirect: '/user/failure',
      failureFlash: true
    }));
    router.get('/success', function(req, res) {
      return res.json('Success!');
    });
    router.get('/failure', function(req, res) {
      return res.json('Failure');
    });
    return app.use('/user', router);
  };

}).call(this);
