// Generated by CoffeeScript 1.7.1
(function() {
  exports.signup = function(passport) {
    return passport.authenticate('local-signup', {
      successRedirect: '/tasks',
      failureFlash: true
    });
  };

  exports.login = function(passport) {
    return passport.authenticate('local-login', {
      successRedirect: '/tasks',
      failureFlash: true
    });
  };

  exports.logout = function(req, res) {
    req.logout();
    return res.redirect('/');
  };

}).call(this);
