// Generated by CoffeeScript 1.7.1
(function() {
  var express;

  express = require('express');

  exports.home = function(req, res) {
    return res.render('home.jade', {
      title: 'Todo',
      styles: ['css/landing.css', 'bootstrap-validator/dist/css/bootstrapValidator.min.css'],
      javascripts: ['bootstrap-validator/dist/js/bootstrapValidator.min.js', 'validate.js']
    });
  };

  exports.tasks = function(req, res) {
    return res.render('tasks.jade', {
      title: 'Todo',
      styles: ['css/main.css'],
      javascripts: []
    });
  };

}).call(this);
