// Generated by CoffeeScript 1.7.1
(function() {
  var express;

  express = require('express');

  exports.home = function(req, res) {
    return res.render('home.jade', {
      title: 'Todo',
      styles: ['css/landing.css']
    });
  };

  exports.tasks = function(req, res) {
    return res.render('tasks.jade', {
      title: 'Todo',
      styles: ['css/main.css']
    });
  };

}).call(this);
