// Generated by CoffeeScript 1.7.1
(function() {
  exports.requiresLogin = function(req, res, next) {
    if (req.isAuthenticated()) {
      return next();
    } else {
      return res.redirect('/');
    }
  };

}).call(this);
