// Generated by CoffeeScript 1.7.1
(function() {
  exports.requiresLogin = function(req, res, next) {
    if (req.isAuthenticated()) {
      return next();
    } else {
      return res.json({
        'response': 'FAIL',
        'errors': ['Sign in required.']
      });
    }
  };

}).call(this);
