// Generated by CoffeeScript 1.7.1
(function() {
  var LocalStrategy, User;

  LocalStrategy = require('passport-local').Strategy;

  User = require('./../models/user');

  module.exports = function(passport) {
    var login_cb, login_strategy, signup_cb, signup_strategy;
    passport.serializeUser(function(user, done) {
      return done(null, user.id);
    });
    passport.deserializeUser(function(id, done) {
      return User.findById(id, function(err, user) {
        return done(err, user);
      });
    });
    signup_cb = function(req, username, password, done) {
      return process.nextTick(function() {
        return User.findOne({
          'local.username': username
        }, function(err, user) {
          var newUser;
          if (err) {
            return done(err);
          }
          if (user) {
            return done(null, false, req.flash('signupMessage', 'That username is already taken.'));
          } else {
            newUser = new User();
            newUser.local.username = username;
            newUser.local.password = newUser.generateHash(password);
            return newUser.save(function(err) {
              if (err) {
                throw err;
              }
              return done(null, newUser);
            });
          }
        });
      });
    };
    signup_strategy = new LocalStrategy({
      passReqToCallback: true
    }, signup_cb);
    passport.use('local-signup', signup_strategy);
    login_cb = function(req, username, password, done) {
      return User.findOne({
        'local.username': username
      }, function(err, user) {
        if (err) {
          return done(err);
        }
        if (!user) {
          return done(null, false, req.flash('loginMessage', 'No user found.'));
        }
        if (!user.validPassword(password)) {
          return done(null, false, req.flash('loginMessage', 'Oops! Wrong password.'));
        }
        return done(null, user);
      });
    };
    login_strategy = new LocalStrategy({
      passReqToCallback: true
    }, login_cb);
    return passport.use('local-login', login_strategy);
  };

}).call(this);
