// Generated by CoffeeScript 1.7.1
(function() {
  var LocalStrategy, User;

  LocalStrategy = require('passport-local').Strategy;

  User = require('./../models/user');

  module.exports = function(passport) {
    var cb, strategy;
    passport.serializeUser(function(user, done) {
      return done(null, user.id);
    });
    passport.deserializeUser(function(id, done) {
      return User.findById(id, function(err, user) {
        return done(err, user);
      });
    });
    cb = function(req, email, password, done) {
      return process.nextTick(function() {
        return User.findOne({
          'local.email': email
        }, function(err, user) {
          var newUser;
          if (err) {
            return done(err);
          }
          if (user) {
            return done(null, false, req.flash('signupMessage', 'That email is already taken.'));
          } else {
            newUser = new User();
            newUser.local.email = email;
            newUser.local.password = newUser.generateHash(password);
            return newUser.save(function(err) {
              if (err) {
                throw err;
              }
              return done(null, newUser);
            });
          }
        });
      });
    };
    strategy = new LocalStrategy({
      usernameField: 'email',
      passwordField: 'password',
      passReqToCallback: true
    }, cb);
    return passport.use('local-signup', strategy);
  };

}).call(this);
