// Generated by CoffeeScript 1.7.1
(function() {
  var Schema, TaskSchema, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  TaskSchema = new Schema({
    text: String,
    completed: Boolean,
    userID: String
  });

  module.exports = mongoose.model('Task', TaskSchema);

}).call(this);
